content.table = {
  WIDTH: 12,
  LENGTH: 40,
  PADDLE_HALF: 1.5,
  NUM_STEPS: 12,
  STEP_SIZE: 1,

  WALL_RESTITUTION: 0.98,
  PADDLE_RESTITUTION: 0.85,
  MAX_BALL_SPEED: 22,
  BALL_SPEED_PEAK: 40,
  BALL_SPEED_RAMP: 0.4,
  BALL_FRICTION: 0.003,

  SWING_POWER: 14,
  SWING_SIDE: 4,
  SWING_ZONE: 4,
  SWING_COOLDOWN: 0.45,

  SERVE_SPEED: 8,
  SERVE_TIMEOUT: 3.0,
  SERVE_WARN_THRESHOLDS: [1.5, 1.2, 0.9, 0.6, 0.3],

  MOVE_HOLD_DELAY: 0.15,
  MOVE_HOLD_REPEAT: 0.08,

  AI_REACTION_DELAY: 0.28,
  AI_SERVE_DELAY: 0.8,

  POWERUP_Y: 1.5,
  POWERUP_SPEED: 13,
  POWERUP_SPAWN_MIN: 13,
  POWERUP_SPAWN_MAX: 25,

  SWING_POWER_VARIANCE: 0.12,
  SWING_STRAIGHT_NOISE: 1.5,
  SWING_SIDE_VARIANCE: 0.18,
  POWERUP_HITBOX: 1.5,

  SHIELD_RESTITUTION: 1.08,

  POWERUP_WIDEN_DURATION: 10,
  POWERUP_WIDEN_MULT: 2,
  POWERUP_SHIELD_DURATION: 10,
  POWERUP_SWING_DURATION: 15,
  POWERUP_SWING_MULT: 1.8,
  POWERUP_FREEZE_MIN: 1.5,
  POWERUP_FREEZE_MAX: 3.2,

  POWERUP_CURVE_DURATION: 20,
  POWERUP_CURVE_SPIN: 1.2,

  POWERUP_BOUNCE_RESTITUTION: 1.75,
  POWERUP_BOUNCE_DURATION: 8,
}
