content.levels = (() => {
  const levels = [
    {
      id: 'receiving',
      name: 'Receiving Bay',
      parMoves: 2,
      map: [
        '#######',
        '#     #',
        '# .$@ #',
        '#     #',
        '#######',
      ],
    },
    {
      id: 'right-angle',
      name: 'Right Angle',
      parMoves: 5,
      map: [
        '#######',
        '#     #',
        '# .$  #',
        '#  @  #',
        '#     #',
        '#######',
      ],
    },
    {
      id: 'double-stack',
      name: 'Double Stack',
      parMoves: 4,
      map: [
        '#######',
        '#     #',
        '# .$  #',
        '# .$@ #',
        '#     #',
        '#######',
      ],
    },
    {
      id: 'split-order',
      name: 'Split Order',
      parMoves: 11,
      map: [
        '########',
        '#      #',
        '# .$.  #',
        '#  $@  #',
        '#  .   #',
        '########',
      ],
    },
    {
      id: 'side-loader',
      name: 'Side Loader',
      parMoves: 13,
      map: [
        '#########',
        '#   .   #',
        '#   $   #',
        '# .$@$. #',
        '#       #',
        '#########',
      ],
    },
    {
      id: 'inventory-hook',
      name: 'Inventory Hook',
      parMoves: 16,
      map: [
        '#########',
        '#   .   #',
        '#  ##$  #',
        '# . @$. #',
        '#       #',
        '#########',
      ],
    },
    {
      id: 'narrow-aisle',
      name: 'Narrow Aisle',
      parMoves: 19,
      map: [
        '#########',
        '# .   . #',
        '# $$#$  #',
        '#   @   #',
        '# .   . #',
        '#########',
      ],
    },
    {
      id: 'packing-loop',
      name: 'Packing Loop',
      parMoves: 22,
      map: [
        '#########',
        '# .   . #',
        '#     $ #',
        '# $# #  #',
        '#@$     #',
        '#  # #$ #',
        '# .   . #',
        '#########',
      ],
    },
    {
      id: 'cold-storage',
      name: 'Cold Storage',
      parMoves: 28,
      map: [
        '##########',
        '# .    . #',
        '# $$  #  #',
        '#  # @   #',
        '#   #  $ #',
        '# .    . #',
        '##########',
      ],
    },
    {
      id: 'forklift-maze',
      name: 'Forklift Maze',
      parMoves: 24,
      map: [
        '##########',
        '# .  # . #',
        '#   $@   #',
        '# $##    #',
        '#     #  #',
        '# $  ##  #',
        '# .  $ . #',
        '##########',
      ],
    },
    {
      id: 'late-shift',
      name: 'Late Shift',
      parMoves: 28,
      map: [
        '#########',
        '# .   . #',
        '# @$ $  #',
        '#  # #  #',
        '#       #',
        '#  # #  #',
        '# .$ $. #',
        '#########',
      ],
    },
    {
      id: 'audit-night',
      name: 'Audit Night',
      parMoves: 31,
      map: [
        '############',
        '# .$  #  . #',
        '#     #    #',
        '# ##  @$ # #',
        '#     $    #',
        '# #     ## #',
        '# .  #   * #',
        '############',
      ],
    },
    {
      id: 'cross-dock',
      name: 'Cross Dock',
      parMoves: 23,
      map: [
        '#########',
        '# .   . #',
        '# @     #',
        '# $# #  #',
        '#       #',
        '#  # #$ #',
        '# .  $. #',
        '#########',
      ],
    },
    {
      id: 'backstock-run',
      name: 'Backstock Run',
      parMoves: 23,
      map: [
        '#########',
        '# .   . #',
        '#  $$   #',
        '#  # #$ #',
        '#       #',
        '#  # #  #',
        '# . $@. #',
        '#########',
      ],
    },
    {
      id: 'racked-corners',
      name: 'Racked Corners',
      parMoves: 24,
      map: [
        '#########',
        '# .  $. #',
        '#       #',
        '#  #$#  #',
        '# $ @   #',
        '#  # #$ #',
        '# .   . #',
        '#########',
      ],
    },
    {
      id: 'conveyor-gap',
      name: 'Conveyor Gap',
      parMoves: 25,
      map: [
        '##########',
        '# .  # . #',
        '#   $  $ #',
        '#  ##    #',
        '#     #  #',
        '#  $ ##  #',
        '# .   $+ #',
        '##########',
      ],
    },
    {
      id: 'pallet-jam',
      name: 'Pallet Jam',
      parMoves: 27,
      map: [
        '##########',
        '# .    . #',
        '#   ## $ #',
        '#        #',
        '# # $  # #',
        '#        #',
        '# .@$ $. #',
        '##########',
      ],
    },
    {
      id: 'security-sweep',
      name: 'Security Sweep',
      parMoves: 28,
      map: [
        '##########',
        '# .  @$. #',
        '# $ ##   #',
        '#        #',
        '# #    # #',
        '#  $   $ #',
        '# .    . #',
        '##########',
      ],
    },
    {
      id: 'compressor-room',
      name: 'Compressor Room',
      parMoves: 28,
      map: [
        '##########',
        '# .  # . #',
        '#    $ $ #',
        '# $##    #',
        '#     #  #',
        '#@$  ##  #',
        '# .    . #',
        '##########',
      ],
    },
    {
      id: 'final-inventory',
      name: 'Final Inventory',
      parMoves: 41,
      map: [
        '###########',
        '# .     . #',
        '# $ # #   #',
        '# #   $ # #',
        '# #     # #',
        '#   # #   #',
        '# . $@$ . #',
        '###########',
      ],
    },
  ]

  return {
    all: () => levels.slice(),
    count: () => levels.length,
    get: (index) => levels[Math.max(0, Math.min(levels.length - 1, index | 0))],
  }
})()
