content.mechs = {
  scout: {
    id: 'scout',
    name: 'Scout',
    description: 'Lightweight recon mech. Very fast and nimble, low health. Machine gun and homing missile. Has a jetpack.',
    size: 1.2,
    maxSpeed: 22,
    acceleration: 14,
    brake: 20,
    turnRate: 2.6,           // rad/s
    mass: 0.7,
    health: 80,
    canJump: false,
    canJetpack: true,
    jumpVelocity: 0,
    jetpackForce: 36,
    jetpackFuel: 4.0,        // seconds
    jetpackRecharge: 2.0,
    primary: 'machinegun',
    secondary: 'homing',
    enginePitch: 1.6,
    engineGain: 0.25,
    stepRate: 3.0,           // steps/second at full speed
    stepVolume: 0.15,
  },
  striker: {
    id: 'striker',
    name: 'Striker',
    description: 'Balanced assault mech. Reliable pistol and brutal melee strike. Can jump.',
    size: 1.6,
    maxSpeed: 16,
    acceleration: 9,
    brake: 14,
    turnRate: 1.9,
    mass: 1.0,
    health: 120,
    canJump: true,
    canJetpack: false,
    jumpVelocity: 14,
    jetpackForce: 0,
    jetpackFuel: 0,
    jetpackRecharge: 0,
    primary: 'pistol',
    secondary: 'melee',
    enginePitch: 1.0,
    engineGain: 0.32,
    stepRate: 2.2,
    stepVolume: 0.28,
  },
  juggernaut: {
    id: 'juggernaut',
    name: 'Juggernaut',
    description: 'Heavy tank mech. Slow but very tough. Rail cannon and shotgun. Cannot jump.',
    size: 2.4,
    maxSpeed: 10,
    acceleration: 4,
    brake: 8,
    turnRate: 1.1,
    mass: 1.8,
    health: 200,
    canJump: false,
    canJetpack: false,
    jumpVelocity: 0,
    jetpackForce: 0,
    jetpackFuel: 0,
    jetpackRecharge: 0,
    primary: 'rail',
    secondary: 'shotgun',
    enginePitch: 0.55,
    engineGain: 0.5,
    stepRate: 1.2,
    stepVolume: 0.55,
  },
  phantom: {
    id: 'phantom',
    name: 'Phantom',
    description: 'Infiltrator mech. Medium speed with a disruptor beam and homing missile. Has a jetpack.',
    size: 1.4,
    maxSpeed: 18,
    acceleration: 10,
    brake: 16,
    turnRate: 2.2,
    mass: 0.85,
    health: 100,
    canJump: false,
    canJetpack: true,
    jumpVelocity: 0,
    jetpackForce: 30,
    jetpackFuel: 3.0,
    jetpackRecharge: 2.5,
    primary: 'disruptor',
    secondary: 'homing',
    enginePitch: 1.3,
    engineGain: 0.22,
    stepRate: 2.6,
    stepVolume: 0.2,
  },
  brawler: {
    id: 'brawler',
    name: 'Brawler',
    description: 'Close-combat specialist. Melee strike and ram boost. Jumps high.',
    size: 1.8,
    maxSpeed: 14,
    acceleration: 8,
    brake: 12,
    turnRate: 1.7,
    mass: 1.2,
    health: 150,
    canJump: true,
    canJetpack: false,
    jumpVelocity: 18,
    jetpackForce: 0,
    jetpackFuel: 0,
    jetpackRecharge: 0,
    primary: 'melee',
    secondary: 'boost',
    enginePitch: 0.8,
    engineGain: 0.38,
    stepRate: 1.8,
    stepVolume: 0.4,
  },
}

content.mechs.list = () => [
  content.mechs.scout,
  content.mechs.striker,
  content.mechs.juggernaut,
  content.mechs.phantom,
  content.mechs.brawler,
]

content.mechs.nameOf = (mech) => mech ? app.i18n.t('mech.' + mech.id + '.name') : ''
content.mechs.descOf = (mech) => mech ? app.i18n.t('mech.' + mech.id + '.description') : ''
