content.weapons = {
  pistol: {
    name: 'Pistol',
    description: 'Straight shot, moderate damage, short cooldown.',
    projectileSpeed: 55,
    range: 80,
    damage: 8,
    cooldown: 0.45,
    autoFire: false,
    homing: false,
    spread: 0,
    count: 1,
    // Audio
    fireSound: 'pistol',
    impactSound: 'impact',
  },
  machinegun: {
    name: 'Machine gun',
    description: 'Rapid fire, low damage per bullet, can hold to fire.',
    projectileSpeed: 50,
    range: 40,
    damage: 2.5,
    cooldown: 0.08,
    autoFire: true,
    homing: false,
    spread: 0.05,
    count: 1,
    fireSound: 'machinegun',
    impactSound: 'impact',
  },
  shotgun: {
    name: 'Shotgun',
    description: 'Spread of pellets, strong up close.',
    projectileSpeed: 45,
    range: 25,
    damage: 3,
    cooldown: 1.1,
    autoFire: false,
    homing: false,
    spread: 0.25,
    count: 6,
    fireSound: 'shotgun',
    impactSound: 'impact',
  },
  rail: {
    name: 'Rail cannon',
    description: 'Huge single slug, very long cooldown.',
    projectileSpeed: 90,
    range: 120,
    damage: 30,
    cooldown: 2.8,
    autoFire: false,
    homing: false,
    spread: 0,
    count: 1,
    fireSound: 'rail',
    impactSound: 'impact',
  },
  homing: {
    name: 'Homing missile',
    description: 'Slow missile that tracks the enemy. Long reload.',
    projectileSpeed: 24,
    range: 140,
    damage: 22,
    cooldown: 3.5,
    autoFire: false,
    homing: true,
    turnRate: 1.8,
    spread: 0,
    count: 1,
    fireSound: 'missile',
    impactSound: 'explosion',
  },
  disruptor: {
    name: 'Disruptor beam',
    description: 'Short-range beam that stuns the enemy engine briefly.',
    projectileSpeed: 90,
    range: 30,
    damage: 4,
    cooldown: 2.0,
    autoFire: false,
    homing: false,
    spread: 0,
    count: 1,
    stunDuration: 1.8,
    fireSound: 'disruptor',
    impactSound: 'disruptor_hit',
  },
  melee: {
    name: 'Melee strike',
    description: 'Powerful close-range hit with knockback.',
    projectileSpeed: 0,
    range: 5,
    damage: 25,
    cooldown: 1.3,
    autoFire: false,
    homing: false,
    spread: 0,
    count: 1,
    knockback: 18,
    fireSound: 'melee',
    impactSound: 'melee_hit',
    melee: true,
  },
  boost: {
    name: 'Ram boost',
    description: 'Short burst of forward thrust. Great for ramming.',
    projectileSpeed: 0,
    range: 0,
    damage: 0,
    cooldown: 4.0,
    autoFire: false,
    homing: false,
    spread: 0,
    count: 0,
    boostDuration: 1.2,
    boostMultiplier: 2.2,
    fireSound: 'boost',
    impactSound: 'none',
    boost: true,
  },
}

content.weapons.nameOf = (id) => id ? app.i18n.t('weapon.' + id + '.name') : ''
content.weapons.descOf = (id) => id ? app.i18n.t('weapon.' + id + '.description') : ''
