/**
 * Networking layer. Thin wrapper over PeerJS so the rest of the app can
 * speak in terms of "host", "join", "broadcast". PeerJS uses its public
 * cloud broker (0.peerjs.com) for signalling, then connects peers with
 * direct WebRTC data channels — no port forwarding, no backend required.
 *
 * Topology: star. The host owns a "room" with a short alphanumeric code.
 * Clients connect to that code. The host is authoritative — it runs the
 * game simulation, broadcasts snapshots, and applies remote inputs.
 *
 * Wire protocol (JSON over the data channel):
 *   c→h  {type: 'hello', name}
 *   c→h  {type: 'input', t, throttle, steering}
 *   c→h  {type: 'leave'}
 *   h→c  {type: 'lobby', peers: [{id, name, isHost}]}
 *   h→c  {type: 'start', selfId, controllers, mode, t0}
 *   h→c  {type: 'snap', f, t, cars: [...], events: [...], scores: {id: n}}
 *   h→c  {type: 'end', reason}
 *   any  {type: 'kick', reason}
 *
 * IDs: each peer in the room is identified by the PeerJS connection peer
 * id. The host's peer id is `bumper-<code>` where <code> is the room
 * code. Client peer ids are auto-generated by PeerJS and meaningless to
 * the game — the player's *car* id is decided by the host at start.
 */
app.net = (() => {
  // -------------------------------------------------------------------
  // ICE / TURN config — change here if the server moves or creds rotate.
  // STUN-only is enough for direct peer-to-peer; TURN is the fallback
  // for symmetric NATs. Both point at our self-hosted coturn on the
  // VPS that serves oriolgomez.com. Credentials are visible to clients
  // by design (WebRTC requires them in the browser); coturn's
  // denied-peer-ip rules limit blast radius if abused.
  // -------------------------------------------------------------------
  const TURN_HOST = 'turn.oriolgomez.com'
  const TURN_PORT = 3478
  const TURNS_PORT = 5349
  const TURN_USER = 'gamesturn'
  const TURN_PASS = 'sin6V0gFokHz78gM0GDfXmat'

  const PEER_ID_PREFIX = 'bumper-'
  // Avoid ambiguous chars (0/O, 1/I/L, etc.) for room codes humans speak
  // out loud or type into a phone keyboard.
  const CODE_CHARSET = 'BCDFGHJKLMNPQRSTVWXZ23456789'
  const CODE_LENGTH = 4
  const VALID_CODE = /^[A-Z0-9]{3,8}$/
  const HEARTBEAT_INTERVAL_MS = 4000
  const PEER_TIMEOUT_MS = 12000

  let peer = null               // PeerJS Peer
  let role = null               // 'host' | 'client' | null
  let myName = ''
  let myPeerId = null
  let myCode = null
  let hostConn = null           // (client) DataConnection to host
  // (host) Map<peerId, {conn, name, lastSeen}>
  const clientConns = new Map()
  let heartbeatTimer = null
  // (client) snapshot of the most recent lobby payload from the host.
  // Used to diff incoming lobbies and synthesize peerJoin / peerLeave
  // events so non-host peers get the same join/leave UI as the host.
  // Set to null until the first lobby arrives — that initial payload
  // is the client's own join, so we suppress the noisy "Alice joined.
  // Bob joined. Charlie joined." reading and announce only deltas.
  let clientLobbyCache = null

  // Event listeners. Names: open, close, peerJoin, peerLeave, message,
  // role, error, lobby. (lobby = updated peer list, host-side only.)
  const listeners = Object.create(null)

  function on(event, cb) {
    if (!listeners[event]) listeners[event] = []
    listeners[event].push(cb)
  }
  function off(event, cb) {
    if (!listeners[event]) return
    listeners[event] = listeners[event].filter((fn) => fn !== cb)
  }
  function fire(event, ...args) {
    const ls = listeners[event]
    if (!ls) return
    for (const fn of ls.slice()) {
      try { fn(...args) } catch (e) { /* swallow */ }
    }
  }

  // -------------------------------------------------------------------
  // Codes
  // -------------------------------------------------------------------

  function generateCode() {
    let code = ''
    for (let i = 0; i < CODE_LENGTH; i++) {
      code += CODE_CHARSET[Math.floor(Math.random() * CODE_CHARSET.length)]
    }
    return code
  }

  function normalizeCode(s) {
    return String(s || '').toUpperCase().replace(/[^A-Z0-9]/g, '')
  }

  function peerIdForCode(code) {
    return PEER_ID_PREFIX + normalizeCode(code).toLowerCase()
  }

  // -------------------------------------------------------------------
  // Lifecycle
  // -------------------------------------------------------------------

  function libAvailable() {
    return typeof window !== 'undefined' && typeof window.Peer === 'function'
  }

  // PeerJS only ships Google STUN by default, which can't punch through
  // symmetric NATs (some mobile carriers, corporate networks, certain
  // ISPs). Point at our self-hosted coturn (see TURN_* constants at the
  // top of this module) so the WebRTC stack has a relay path when
  // direct peer-to-peer is impossible. STUN is tried first, so most
  // connections never hit the relay; TURN only kicks in when STUN
  // fails. Both UDP and TCP transports are listed so corporate firewalls
  // that drop UDP can still get through.
  // Toggle in console: localStorage.bumperNetDebug = '1' to see PeerJS
  // logs + ICE state on the underlying RTCPeerConnection. Default is 0
  // (silent) for shipped builds. When debugging connection failures, the
  // most useful signal is which candidate types appear in ICE gathering:
  //   host  — local LAN address (always present)
  //   srflx — public address discovered via STUN (means STUN works)
  //   relay — TURN-allocated address (means TURN works)
  // No relay candidates + symmetric NAT = no path = silent timeout.
  const isDebug = () => {
    try { return window.localStorage && window.localStorage.bumperNetDebug === '1' } catch (e) { return false }
  }

  const peerOptions = () => ({
    debug: isDebug() ? 2 : 0,
    config: {
      iceServers: [
        {urls: `stun:${TURN_HOST}:${TURN_PORT}`},
        {urls: 'stun:stun.l.google.com:19302'},
        {
          urls: `turn:${TURN_HOST}:${TURN_PORT}?transport=udp`,
          username: TURN_USER,
          credential: TURN_PASS,
        },
        {
          urls: `turn:${TURN_HOST}:${TURN_PORT}?transport=tcp`,
          username: TURN_USER,
          credential: TURN_PASS,
        },
        // Last-resort relay for clients on networks that block everything
        // except TLS-on-non-443 (some hotels, corporate guest wifi).
        // turns: = TURN-over-TLS, served on 5349 with the same Let's
        // Encrypt cert as the rest of the domain.
        {
          urls: `turns:${TURN_HOST}:${TURNS_PORT}?transport=tcp`,
          username: TURN_USER,
          credential: TURN_PASS,
        },
      ],
      iceCandidatePoolSize: 2,
    },
  })

  // Hook the DataConnection's underlying RTCPeerConnection so we can see
  // what's happening during the open window. PeerJS exposes
  // `dataConnection.peerConnection` in 1.x; older builds may put it under
  // `_negotiator._pc`. Tolerate both, and only attach when debug is on.
  function attachIceDiagnostics(conn, label) {
    if (!conn || !isDebug()) return
    let pc = conn.peerConnection || (conn._negotiator && conn._negotiator._pc)
    // peerConnection isn't always assigned synchronously; poll briefly.
    const tryAttach = (tries = 0) => {
      pc = pc || conn.peerConnection || (conn._negotiator && conn._negotiator._pc)
      if (!pc) {
        if (tries < 20) setTimeout(() => tryAttach(tries + 1), 100)
        return
      }
      const tag = `[net:${label}]`
      console.log(tag, 'pc attached')
      pc.addEventListener('icecandidate', (e) => {
        if (!e.candidate) { console.log(tag, 'icegather: end'); return }
        const c = e.candidate.candidate || ''
        const m = c.match(/typ (\S+)/)
        const type = m ? m[1] : '?'
        console.log(tag, `cand ${type}`, c)
      })
      pc.addEventListener('icegatheringstatechange', () => {
        console.log(tag, 'iceGathering:', pc.iceGatheringState)
      })
      pc.addEventListener('iceconnectionstatechange', () => {
        console.log(tag, 'iceConnection:', pc.iceConnectionState)
        if (pc.iceConnectionState === 'connected' || pc.iceConnectionState === 'completed') {
          if (pc.getStats) pc.getStats(null).then((stats) => {
            stats.forEach((r) => {
              if (r.type === 'candidate-pair' && r.nominated && r.state === 'succeeded') {
                const local = stats.get(r.localCandidateId)
                const remote = stats.get(r.remoteCandidateId)
                console.log(tag, 'selected pair:',
                  local && local.candidateType, '↔', remote && remote.candidateType,
                  '(', local && local.protocol, ')')
              }
            })
          }).catch(() => {})
        }
      })
      pc.addEventListener('connectionstatechange', () => {
        console.log(tag, 'pc state:', pc.connectionState)
      })
    }
    tryAttach()
  }

  // PeerJS DataConnection.send() doesn't throw when the channel isn't
  // open — it emits a NotOpenYet error on the connection, which our
  // conn.on('error') listener surfaces through fire('error'), which the
  // multiplayer screen announces to the user. So a try/catch around
  // .send() catches nothing useful; we have to actually check `conn.open`
  // first. The window where this matters is between peer.on('connection')
  // (host) / peer.connect() (client) and the data channel finishing
  // negotiation — heartbeats, lobby sends, and disconnect kicks can all
  // fire during that window.
  function safeSend(conn, msg) {
    if (!conn || !conn.open) return false
    try { conn.send(msg); return true } catch (e) { return false }
  }

  // -------------------------------------------------------------------
  // Client-side lobby diff
  // -------------------------------------------------------------------
  // The host fires its own peerJoin/peerLeave when clients connect or
  // disconnect, but those events never reach other clients — clients
  // only receive a refreshed `lobby` payload. Without this diff, every
  // non-host peer would silently miss the "Alice joined" / "Alice left"
  // surface in the lobby (and the matching SFX). We diff each new
  // lobby against the previous one and re-fire the same events the
  // host fires locally so the multiplayer screen handlers can run on
  // every peer with no extra wiring.
  //
  // The first payload after joining is suppressed: it represents the
  // peer's own arrival into a lobby that already has people in it, so
  // re-firing peerJoin for every existing peer would read out the
  // whole roster as "joining now."
  function diffLobbyOnClient(peers) {
    const next = new Map((peers || []).map((p) => [p.peerId, p]))
    const prev = clientLobbyCache
    clientLobbyCache = next

    if (!prev) return  // first lobby after join — suppress

    for (const [peerId, p] of next) {
      if (!prev.has(peerId)) {
        fire('peerJoin', {peerId, name: p.name})
      }
    }
    for (const [peerId, p] of prev) {
      if (!next.has(peerId)) {
        fire('peerLeave', {peerId, name: p.name})
      }
    }
  }

  function disconnect(reason = 'left') {
    stopHeartbeat()
    clientLobbyCache = null
    try {
      if (role === 'host') {
        for (const {conn} of clientConns.values()) {
          safeSend(conn, {type: 'kick', reason})
          try { conn.close() } catch (e) {}
        }
      } else if (role === 'client' && hostConn) {
        safeSend(hostConn, {type: 'leave'})
        try { hostConn.close() } catch (e) {}
      }
    } finally {
      clientConns.clear()
      hostConn = null
      if (peer) {
        try { peer.destroy() } catch (e) {}
      }
      peer = null
      const wasRole = role
      role = null
      myCode = null
      myPeerId = null
      if (wasRole) fire('role', null)
      fire('close', {reason})
    }
  }

  // -------------------------------------------------------------------
  // Host
  // -------------------------------------------------------------------

  /**
   * Start hosting a room.
   * @returns {Promise<{code, peerId}>} resolves once the broker has
   *   accepted the room id; rejects on broker error or unavailable id.
   */
  async function host({name = 'Host', code} = {}) {
    if (!libAvailable()) {
      throw new Error('Networking is unavailable. PeerJS failed to load.')
    }
    if (peer) disconnect('reconnect')

    myName = String(name || 'Host').slice(0, 16) || 'Host'
    myCode = code ? normalizeCode(code) : generateCode()
    if (!VALID_CODE.test(myCode)) myCode = generateCode()

    return new Promise((resolve, reject) => {
      let settled = false
      const id = peerIdForCode(myCode)
      try {
        peer = new window.Peer(id, peerOptions())
      } catch (e) {
        reject(e)
        return
      }

      peer.on('open', (openId) => {
        if (settled) return
        settled = true
        myPeerId = openId
        role = 'host'
        // Empty lobby; host is in it.
        fire('role', 'host')
        broadcastLobby()
        startHeartbeat()
        resolve({code: myCode, peerId: openId})
      })

      peer.on('error', (err) => {
        const code = err && err.type
        if (!settled) {
          settled = true
          // Common errors: 'unavailable-id' (room code already in use),
          // 'network'/'server-error' (broker unreachable).
          peer = null
          myCode = null
          reject(new Error(humanError(code) || (err && err.message) || 'Connection error.'))
          return
        }
        // Errors after open: surface but stay alive.
        fire('error', {code, message: humanError(code) || (err && err.message)})
      })

      peer.on('connection', (conn) => {
        // Client connecting to us.
        attachClientConnection(conn)
      })

      peer.on('disconnected', () => {
        // Lost broker socket — try to reconnect (peers stay live; only
        // matters for accepting NEW connections).
        try { peer.reconnect() } catch (e) {}
      })
    })
  }

  function attachClientConnection(conn) {
    const peerId = conn.peer

    // Capacity check: 1 host + 5 clients = 6 max.
    if (clientConns.size >= 5) {
      conn.on('open', () => {
        safeSend(conn, {type: 'kick', reason: 'full'})
        try { conn.close() } catch (e) {}
      })
      return
    }

    const record = {conn, name: peerId.slice(0, 6), lastSeen: Date.now(), helloed: false}
    clientConns.set(peerId, record)

    attachIceDiagnostics(conn, `host<-${peerId.slice(0, 6)}`)

    conn.on('open', () => {
      record.lastSeen = Date.now()
      // Wait for the client's hello before announcing them in the lobby
      // (so we can include their name).
    })

    conn.on('data', (msg) => {
      if (!msg || typeof msg !== 'object') return
      record.lastSeen = Date.now()
      if (msg.type === 'hello') {
        record.name = String(msg.name || 'Player').slice(0, 16) || 'Player'
        if (!record.helloed) {
          record.helloed = true
          fire('peerJoin', {peerId, name: record.name})
          broadcastLobby()
          fire('lobby', getLobby())
        }
        return
      }
      if (msg.type === 'leave') {
        try { conn.close() } catch (e) {}
        return
      }
      if (msg.type === 'pong') {
        return
      }
      // Forward other messages (input etc.) to listeners.
      fire('message', {peerId, name: record.name, msg})
    })

    conn.on('close', () => {
      // Only announce a leave for peers that actually made it into the
      // lobby (helloed). A conn that closes before hello arrives is a
      // failed handshake — no peerJoin ever fired, so a peerLeave would
      // surface as a confusing "9df593 left" with no matching join.
      const wasInLobby = record.helloed
      if (clientConns.delete(peerId)) {
        if (wasInLobby) {
          fire('peerLeave', {peerId, name: record.name})
          broadcastLobby()
          fire('lobby', getLobby())
        }
      }
    })

    conn.on('error', (err) => {
      fire('error', {code: err && err.type, message: (err && err.message) || 'Connection error.'})
    })
  }

  function broadcastLobby() {
    if (role !== 'host') return
    const lobby = getLobby()
    const payload = {type: 'lobby', peers: lobby}
    for (const {conn, helloed} of clientConns.values()) {
      if (!helloed) continue
      safeSend(conn, payload)
    }
  }

  function getLobby() {
    if (role === 'host') {
      const peers = [{peerId: myPeerId, name: myName, isHost: true}]
      for (const [peerId, rec] of clientConns) {
        if (!rec.helloed) continue
        peers.push({peerId, name: rec.name, isHost: false})
      }
      return peers
    }
    // Clients have lobby data only when host has sent it; cached on
    // last 'lobby' message. We rebroadcast unchanged via fire('lobby').
    return []
  }

  // -------------------------------------------------------------------
  // Client
  // -------------------------------------------------------------------

  async function join({name = 'Player', code}) {
    if (!libAvailable()) {
      throw new Error('Networking is unavailable. PeerJS failed to load.')
    }
    const norm = normalizeCode(code)
    if (!VALID_CODE.test(norm)) {
      throw new Error('Room code must be 3 to 8 letters or digits.')
    }
    if (peer) disconnect('reconnect')

    myName = String(name || 'Player').slice(0, 16) || 'Player'
    myCode = norm

    return new Promise((resolve, reject) => {
      let settled = false
      try {
        peer = new window.Peer(peerOptions())
      } catch (e) {
        reject(e)
        return
      }

      const fail = (err) => {
        if (settled) return
        settled = true
        const code = err && err.type
        try { peer && peer.destroy() } catch (e) {}
        peer = null
        myCode = null
        reject(new Error(humanError(code) || (err && err.message) || 'Connection error.'))
      }

      peer.on('error', (err) => {
        if (!settled) { fail(err); return }
        fire('error', {code: err && err.type, message: humanError(err && err.type) || (err && err.message)})
      })

      peer.on('open', (openId) => {
        myPeerId = openId
        const targetId = peerIdForCode(myCode)
        const conn = peer.connect(targetId, {
          reliable: true,
          metadata: {name: myName},
        })
        hostConn = conn

        attachIceDiagnostics(conn, 'client->host')

        // 20s, not 8s. TURN allocation + ICE checks + DTLS handshake on a
        // slow link or a relay-only path can run past 8s, especially when
        // STUN candidates fail and the stack falls back through the TURN
        // entries one at a time. False-positive "Could not reach host"
        // timeouts on a working but slow path were biting real users.
        const openTimer = setTimeout(() => {
          if (!settled) fail({type: 'timeout', message: 'Could not reach host.'})
        }, 20000)

        conn.on('open', () => {
          clearTimeout(openTimer)
          if (settled) return
          settled = true
          role = 'client'
          fire('role', 'client')
          safeSend(conn, {type: 'hello', name: myName})
          startHeartbeat()
          resolve({code: myCode, peerId: openId})
        })

        conn.on('data', (msg) => {
          if (!msg || typeof msg !== 'object') return
          if (msg.type === 'lobby') {
            const peers = Array.isArray(msg.peers) ? msg.peers : []
            diffLobbyOnClient(peers)
            fire('lobby', peers)
            return
          }
          if (msg.type === 'kick') {
            fire('error', {code: 'kicked', message: humanError('kicked-' + (msg.reason || ''))})
            disconnect(msg.reason || 'kicked')
            return
          }
          if (msg.type === 'pong') return
          fire('message', {peerId: targetId, msg})
        })

        conn.on('close', () => {
          if (role === 'client') {
            fire('error', {code: 'host-closed', message: 'Disconnected from host.'})
            disconnect('host-closed')
          }
        })

        conn.on('error', (err) => {
          if (!settled) { fail(err); return }
          fire('error', {code: err && err.type, message: humanError(err && err.type) || (err && err.message)})
        })
      })
    })
  }

  // -------------------------------------------------------------------
  // Send
  // -------------------------------------------------------------------

  function send(peerId, msg) {
    if (role === 'host') {
      const rec = clientConns.get(peerId)
      if (!rec) return false
      return safeSend(rec.conn, msg)
    }
    if (role === 'client') {
      return safeSend(hostConn, msg)
    }
    return false
  }

  function broadcast(msg) {
    if (role === 'host') {
      let n = 0
      for (const {conn, helloed} of clientConns.values()) {
        if (!helloed) continue
        if (safeSend(conn, msg)) n++
      }
      return n
    }
    if (role === 'client') {
      return safeSend(hostConn, msg) ? 1 : 0
    }
    return 0
  }

  // sendToHost is just broadcast for clients; explicit for clarity.
  function sendToHost(msg) {
    if (role !== 'client') return false
    return safeSend(hostConn, msg)
  }

  // -------------------------------------------------------------------
  // Heartbeat (drop stale peers)
  // -------------------------------------------------------------------

  function startHeartbeat() {
    stopHeartbeat()
    heartbeatTimer = setInterval(() => {
      const now = Date.now()
      if (role === 'host') {
        // Send pings; drop peers that haven't talked back in PEER_TIMEOUT_MS.
        // safeSend skips conns whose data channel hasn't opened yet (the
        // 4s heartbeat tick can otherwise fall inside the open-window).
        for (const [peerId, rec] of [...clientConns]) {
          safeSend(rec.conn, {type: 'ping', t: now})
          if (now - rec.lastSeen > PEER_TIMEOUT_MS) {
            const wasInLobby = rec.helloed
            try { rec.conn.close() } catch (e) {}
            if (clientConns.delete(peerId)) {
              if (wasInLobby) {
                fire('peerLeave', {peerId, name: rec.name, reason: 'timeout'})
                broadcastLobby()
                fire('lobby', getLobby())
              }
            }
          }
        }
      } else if (role === 'client') {
        safeSend(hostConn, {type: 'ping', t: now})
      }
    }, HEARTBEAT_INTERVAL_MS)
  }

  function stopHeartbeat() {
    if (heartbeatTimer) {
      clearInterval(heartbeatTimer)
      heartbeatTimer = null
    }
  }

  // -------------------------------------------------------------------
  // Misc
  // -------------------------------------------------------------------

  function humanError(code) {
    switch (code) {
      case 'unavailable-id': return 'That room code is taken. Try another.'
      case 'peer-unavailable': return 'No room with that code. Check the code.'
      case 'network': return 'Network error. Check your connection.'
      case 'server-error':
      case 'socket-error':
      case 'socket-closed':
        return 'The matchmaking server is unreachable. Try again later.'
      case 'browser-incompatible': return 'Your browser does not support WebRTC.'
      case 'webrtc': return 'WebRTC error. Try refreshing.'
      case 'timeout': return 'Connection timed out.'
      case 'kicked-full': return 'That room is full.'
      case 'kicked-host-left': return 'The host left the room.'
      case 'kicked-game-over': return 'Round ended.'
      case 'host-closed': return 'Disconnected from host.'
      default: return null
    }
  }

  function getPeers() {
    if (role === 'host') return getLobby()
    return []
  }

  return {
    host,
    join,
    disconnect,
    send,
    broadcast,
    sendToHost,
    on,
    off,
    role: () => role,
    code: () => myCode,
    name: () => myName,
    peerId: () => myPeerId,
    peers: getPeers,
    libAvailable,
    normalizeCode,
  }
})()
